/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotel;

import java.awt.Desktop;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JTabbedPane;

/**
 *
 * @author ROEI
 */
public class Homepage extends javax.swing.JFrame {

    /**
     * Creates new form Homepage
     */
    public Homepage() {
        initComponents();
        setDateAndTime();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        newres = new javax.swing.JLabel();
        hotelstats = new javax.swing.JLabel();
        roomlistbtn = new javax.swing.JLabel();
        newcheckout = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(890, 700));
        setResizable(false);

        jPanel1.setOpaque(false);
        jPanel1.setLayout(null);

        newres.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                newresMouseClicked(evt);
            }
        });
        jPanel1.add(newres);
        newres.setBounds(0, 280, 180, 40);

        hotelstats.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hotelstatsMouseClicked(evt);
            }
        });
        jPanel1.add(hotelstats);
        hotelstats.setBounds(0, 210, 180, 40);

        roomlistbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                roomlistbtnMouseClicked(evt);
            }
        });
        jPanel1.add(roomlistbtn);
        roomlistbtn.setBounds(0, 360, 180, 40);

        newcheckout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                newcheckoutMouseClicked(evt);
            }
        });
        jPanel1.add(newcheckout);
        newcheckout.setBounds(0, 430, 190, 40);

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(234, 236, 236));
        jTextField1.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("111");
        jTextField1.setBorder(null);
        jTextField1.setSelectedTextColor(new java.awt.Color(234, 236, 236));
        jTextField1.setSelectionColor(new java.awt.Color(234, 236, 236));
        jPanel1.add(jTextField1);
        jTextField1.setBounds(300, 280, 450, 50);

        jTextField2.setEditable(false);
        jTextField2.setBackground(new java.awt.Color(234, 236, 236));
        jTextField2.setFont(new java.awt.Font("Arial Black", 0, 16)); // NOI18N
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.setText("111");
        jTextField2.setBorder(null);
        jTextField2.setSelectedTextColor(new java.awt.Color(234, 236, 236));
        jTextField2.setSelectionColor(new java.awt.Color(234, 236, 236));
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField2);
        jTextField2.setBounds(320, 330, 420, 40);
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(240, 250, 590, 40);
        jPanel1.add(jSeparator2);
        jSeparator2.setBounds(240, 390, 590, 40);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/home.png"))); // NOI18N
        jLabel6.setPreferredSize(new java.awt.Dimension(892, 700));
        jPanel1.add(jLabel6);
        jLabel6.setBounds(0, 0, 910, 668);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 890, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 662, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newresMouseClicked
        try {
            new NewRes().setVisible(true);
            
            
        } catch (Exception ex) {
            Logger.getLogger(Homepage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_newresMouseClicked

    private void hotelstatsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hotelstatsMouseClicked
              try {
            new HotelStats().setVisible(true);
            
            
        } catch (Exception ex) {
            Logger.getLogger(Homepage.class.getName()).log(Level.SEVERE, null, ex);
        }
       
       
    }//GEN-LAST:event_hotelstatsMouseClicked

    private void roomlistbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roomlistbtnMouseClicked
        try {
            new RoomList().setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(Homepage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_roomlistbtnMouseClicked

    private void newcheckoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newcheckoutMouseClicked
        try {
            new CheckOut().setVisible(true);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Homepage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_newcheckoutMouseClicked

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               
                new Homepage().setVisible(true);
            }
        });
    }

    public void switchPanel(JFrame frame){
    
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel hotelstats;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel newcheckout;
    private javax.swing.JLabel newres;
    private javax.swing.JLabel roomlistbtn;
    // End of variables declaration//GEN-END:variables

    private void setDateAndTime() {
       
SimpleDateFormat formatter= new SimpleDateFormat("dd-MM-yyyy ',' HH:mm");
        Date date = new Date(System.currentTimeMillis());
jTextField2.setText(formatter.format(date));

Calendar c = Calendar.getInstance();
int timeOfDay = c.get(Calendar.HOUR_OF_DAY);

if(timeOfDay >= 0 && timeOfDay < 12){
   jTextField1.setText("Good Morning!");
}else if(timeOfDay >= 12 && timeOfDay < 16){
   jTextField1.setText("Good Afternoon!");
}else if(timeOfDay >= 16 && timeOfDay < 21){
    jTextField1.setText("Good Evening!");
}else if(timeOfDay >= 21 && timeOfDay < 24){
    jTextField1.setText("Good Night!");
}

    }
}
