/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotel;

import static hotel.NewRes.con;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.*;

/**
 *
 * @author ROEI
 */
public class HotelStats extends javax.swing.JFrame {

    /**
     * Creates new form HotelStats
     */
    public HotelStats() throws Exception {
        initComponents();
        try {
            Connect();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(NewRes.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        avilablerooms = new javax.swing.JTextField();
        guestinhotel = new javax.swing.JTextField();
        suitesleft = new javax.swing.JTextField();
        twoandmore = new javax.swing.JTextField();
        roomfortwo = new javax.swing.JTextField();
        back = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(890, 700));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Total Gusets in hotel:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(400, 350, 170, 20);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Total Hotel Rooms: 100");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(310, 130, 260, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Total Avilable Hotel Rooms:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(350, 320, 210, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Room for 2 and above left:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(360, 410, 210, 20);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Suites left:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(470, 440, 100, 20);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Room For 2 left:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(430, 380, 140, 20);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setText("Hotel Current Stats");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(410, 40, 240, 90);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Total Hotel Room for 2 and above 50");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(310, 190, 280, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Total Hotel Suites : 10");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(310, 220, 260, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Total Hotel Room for 2: 40");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(310, 160, 260, 30);

        jLabel11.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 51), 2)));
        getContentPane().add(jLabel11);
        jLabel11.setBounds(290, 120, 520, 140);

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(540, 520, 160, 40);

        jButton2.setText("Print");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(370, 520, 160, 40);

        avilablerooms.setEditable(false);
        avilablerooms.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        avilablerooms.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        avilablerooms.setMaximumSize(new java.awt.Dimension(800, 600));
        avilablerooms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                avilableroomsActionPerformed(evt);
            }
        });
        getContentPane().add(avilablerooms);
        avilablerooms.setBounds(560, 320, 90, 20);

        guestinhotel.setEditable(false);
        guestinhotel.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        guestinhotel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        guestinhotel.setMaximumSize(new java.awt.Dimension(800, 600));
        guestinhotel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guestinhotelActionPerformed(evt);
            }
        });
        getContentPane().add(guestinhotel);
        guestinhotel.setBounds(560, 350, 90, 20);

        suitesleft.setEditable(false);
        suitesleft.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        suitesleft.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        suitesleft.setMaximumSize(new java.awt.Dimension(800, 600));
        suitesleft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suitesleftActionPerformed(evt);
            }
        });
        getContentPane().add(suitesleft);
        suitesleft.setBounds(560, 440, 90, 20);

        twoandmore.setEditable(false);
        twoandmore.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        twoandmore.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        twoandmore.setMaximumSize(new java.awt.Dimension(800, 600));
        twoandmore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twoandmoreActionPerformed(evt);
            }
        });
        getContentPane().add(twoandmore);
        twoandmore.setBounds(560, 410, 90, 20);

        roomfortwo.setEditable(false);
        roomfortwo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        roomfortwo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        roomfortwo.setMaximumSize(new java.awt.Dimension(800, 600));
        roomfortwo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roomfortwoActionPerformed(evt);
            }
        });
        getContentPane().add(roomfortwo);
        roomfortwo.setBounds(560, 380, 90, 20);

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/stats.png"))); // NOI18N
        back.setText("jLabel6");
        getContentPane().add(back);
        back.setBounds(0, 0, 890, 660);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void avilableroomsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_avilableroomsActionPerformed

    }//GEN-LAST:event_avilableroomsActionPerformed

    private void guestinhotelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guestinhotelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_guestinhotelActionPerformed

    private void suitesleftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suitesleftActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_suitesleftActionPerformed

    private void twoandmoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twoandmoreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_twoandmoreActionPerformed

    private void roomfortwoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomfortwoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_roomfortwoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed
    public void Connect() throws Exception {
        Class.forName("com.mysql.cj.jdbc.Driver");
        String url = "jdbc:mysql://127.0.0.1:3306/clients?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=CONVERT_TO_NULL&serverTimezone=GMT";
        int total = 0;
        int totalfor2 = 40;
        int totalfor2plus = 50;
        int toatalsuits = 10;
        int empty = 100;
        try {
            con = DriverManager.getConnection(url, "root", "root");
            System.out.println("ok");
            PreparedStatement st = con.prepareStatement("select *from clients");
            ResultSet rs = st.executeQuery();

            while (rs.next()) {
                total += Integer.parseInt(rs.getString("number_of_poeple"));
            }

            guestinhotel.setText(Integer.toString(total));

            rs = st.executeQuery();

            while (rs.next()) {
                totalfor2 = Integer.parseInt(rs.getString("roomsfortwo"));
                totalfor2plus = Integer.parseInt(rs.getString("roomformorethantwo"));
                toatalsuits = Integer.parseInt(rs.getString("suits"));
                empty --;

            }

            roomfortwo.setText(Integer.toString(totalfor2));
            twoandmore.setText(Integer.toString(totalfor2plus));
            suitesleft.setText(Integer.toString(toatalsuits));
            avilablerooms.setText(Integer.toString(empty));

        } catch (SQLException e) {
            System.err.println(e);
        }

    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HotelStats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HotelStats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HotelStats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HotelStats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new HotelStats().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(HotelStats.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField avilablerooms;
    private javax.swing.JLabel back;
    private javax.swing.JTextField guestinhotel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField roomfortwo;
    private javax.swing.JTextField suitesleft;
    private javax.swing.JTextField twoandmore;
    // End of variables declaration//GEN-END:variables
}
